# Generated by Django 5.2.7 on 2025-10-20 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profesionales',
            fields=[
                ('id_profesional', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('especialidad', models.CharField(blank=True, max_length=100, null=True)),
                ('correo', models.CharField(max_length=100, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'profesionales',
            },
        ),
        migrations.CreateModel(
            name='Recursos',
            fields=[
                ('id_recurso', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('enlace', models.CharField(blank=True, max_length=255, null=True)),
                ('categoria', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'recursos',
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.CharField(max_length=100, unique=True)),
                ('contraseña', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='Solicitudes',
            fields=[
                ('id_solicitud', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('fecha', models.IntegerField()),
                ('estado', models.CharField(max_length=20)),
                ('fk_profesional', models.ForeignKey(db_column='FK_PROFESIONAL', on_delete=django.db.models.deletion.DO_NOTHING, to='App_V.profesionales')),
                ('fk_usuario', models.ForeignKey(db_column='FK_USUARIO', on_delete=django.db.models.deletion.DO_NOTHING, to='App_V.usuarios')),
            ],
            options={
                'db_table': 'solicitudes',
            },
        ),
    ]
