# Generated by Django 5.2.7 on 2025-11-27 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_V', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='rol',
            field=models.CharField(choices=[('usuario', 'Usuarios'), ('profesional', 'Profesionales'), ('admin', 'Administrador')], default='usuario', max_length=20),
        ),
        migrations.AlterField(
            model_name='solicitudes',
            name='fk_profesional',
            field=models.ForeignKey(db_column='FK_PROFESIONAL', null=True, on_delete=django.db.models.deletion.SET_NULL, to='App_V.profesionales'),
        ),
        migrations.AlterField(
            model_name='solicitudes',
            name='fk_usuario',
            field=models.ForeignKey(db_column='FK_USUARIO', on_delete=django.db.models.deletion.CASCADE, to='App_V.usuarios'),
        ),
    ]
