# Generated by Django 5.2.7 on 2025-11-27 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_V', '0002_usuarios_rol_alter_solicitudes_fk_profesional_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='correo',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='rol',
            field=models.CharField(choices=[('usuario', 'Usuario'), ('profesional', 'Profesional'), ('admin', 'Administrador')], default='usuario', max_length=20),
        ),
    ]
